// 

export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

export const FETCH_NEWS_ITEM_REQUEST = 'FETCH_NEWS_ITEM_REQUEST';
export const FETCH_NEWS_ITEM_SUCCESS = 'FETCH_NEWS_ITEM_SUCCESS';
export const FETCH_NEWS_ITEM_FAILURE = 'FETCH_NEWS_ITEM_FAILURE';
export const CLEAR_NEWS_ITEM = 'CLEAR_NEWS_ITEM';

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const FETCH_NESTED_COMMENTS_REQUEST = 'FETCH_NESTED_COMMENTS_REQUEST';
export const FETCH_NESTED_COMMENTS_SUCCESS = 'FETCH_NESTED_COMMENTS_SUCCESS';
export const FETCH_NESTED_COMMENTS_FAILURE = 'FETCH_NESTED_COMMENTS_FAILURE';
